[versions]
agp = "9.3.2"
kotlin = "2.4.10"
coreKtx = "1.19.0"
appcompat = "1.8.0"
material = "1.14.0"
constraintlayout = "2.2.2"
androidxRoom = "2.8.4"
jsch = "2.28.7"
bouncycastle = "1.85"
bcprov = "1.85.2"

[libraries]
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
androidx-constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "constraintlayout" }
androidx-room-rt = { group = "androidx.room", name = "room-runtime", version.ref = "androidxRoom" }
androidx-room-ksp = { group = "androidx.room", name = "room-compiler", version.ref = "androidxRoom" }
jsch = { module = "com.github.mwiede:jsch", version.ref = "jsch" }
bcpkix-jdk18on = { module = "org.bouncycastle:bcpkix-jdk18on", version.ref = "bouncycastle" }
bcprov-jdk18on = { module = "org.bouncycastle:bcprov-jdk18on", version.ref = "bcprov" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
ksp = { id = "com.google.devtools.ksp", version = "2.3.11" }
